version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=taskmaster_user
      - DB_PASSWORD=iz-ts_9UiN4fyc9D
      - DB_NAME=taskmasterpro_dev
      - JWT_SECRET=nk90631a4xTfEEaxqdS+8Fgk/gfEHlWKtGA0zcPcM77pt86lweCyTF2pE1PPACpsKIPc3Jbei+sKnf7KH9LXXw==
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=taskmaster_user
      - POSTGRES_PASSWORD=GUm8Teth
      - POSTGRES_DB=taskmasterpro_dev
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
